---
title: '1: Data Sources'
editor:
  markdown:
    wrap: sentence
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

## **Source:**

The dataset is sourced from the New York City Open Data platform, specifically provided by the New York City Police Department (NYPD).
This platform is a part of the city's initiative to increase public access to data generated by various departments of NYC.
The New York City Police Department (NYPD) is responsible for compiling and maintaining this dataset.
The NYPD is the largest and one of the oldest municipal police departments in the United States, with primary responsibilities in law enforcement and investigation within the five boroughs of New York City.

<https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Crashes/h9gi-nx95/about_data>

## Format:

The dataset is available in multiple formats, including CSV for bulk downloads and JSON for API access.
The API, provided through the Socrata Open Data API (SODA), allows for real-time data retrieval and querying specific data points based on various parameters such as date, location, and type of collision.

## Nature of the Data:

The dataset contains detailed records of motor vehicle collisions reported to the NYPD.
Each record includes information such as date and time of the collision, location (latitude and longitude coordinates, borough, zip code, street names), involved parties (number of persons injured, number of persons killed, number of pedestrians involved, cyclists, and motorists), type of vehicles involved, and contributing factors to the collision.

The data covers all reported motor vehicle collisions in New York City since July 2012 and is updated daily to include new incidents.
This ensures the dataset is a comprehensive and up-to-date source for analyzing trends in road safety and vehicle collisions within the city.

## Key Features of the Data:

-   **Temporal Data:** Date and time of collisions allow for time-series analysis to identify trends over different periods.
-   **Spatial Data:** Geographic coordinates and location descriptions enable spatial analysis to identify high-risk areas and collision hotspots.
-   **Categorical Data:** Information on the type of vehicles involved and contributing factors to collisions supports categorical analysis for identifying common causes and outcomes.
-   **Quantitative Data:** Counts of injured and killed persons provide quantitative measures to assess the severity and impact of collisions.
